ALTER TABLE "Product"
ADD COLUMN "isTopCollection" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "topCollectionOrder" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "isNewArrival" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "newArrivalOrder" INTEGER NOT NULL DEFAULT 0;
