import type { Metadata } from 'next'
import styles from '../legal.module.css'

export const metadata: Metadata = { title: 'Terms of service', description: 'The terms that apply when you use the NEMO store.' }

export default function TermsPage() {
  return <main className={styles.page}><header className={styles.hero}><p className={styles.kicker}>NEMO / Terms</p><h1>Simple terms, clearly stated.</h1><p className={styles.lead}>These terms explain the ground rules for using NEMO and placing an order with us.</p></header><div className={styles.content}>
    <section className={styles.section}><p className={styles.index}>01</p><div><h2>Using the store</h2><p>You may use NEMO for lawful personal shopping. Keep your account details accurate and protect your login credentials. You are responsible for activity performed through your account.</p><p>Do not misuse the site, interfere with its operation, attempt unauthorized access, or submit content that is unlawful, abusive, misleading, or infringes another person’s rights.</p></div></section>
    <section className={styles.section}><p className={styles.index}>02</p><div><h2>Products and orders</h2><p>We aim to keep product descriptions, images, prices, availability, and measurements accurate. Colors may appear differently on different screens. An item in your cart is not reserved until your order is accepted.</p><p>We may correct errors, limit quantities, or cancel an order when an item is unavailable, incorrectly priced, or affected by suspected fraud. If we cancel a paid order, we will arrange an appropriate refund.</p></div></section>
    <section className={styles.section}><p className={styles.index}>03</p><div><h2>Payment and delivery</h2><p>Available payment methods, delivery charges, and estimated delivery times are shown during checkout. For cash-on-delivery orders, payment is due when the order arrives. Delivery estimates are not guarantees and may change because of events outside our control.</p></div></section>
    <section className={styles.section}><p className={styles.index}>04</p><div><h2>Returns and support</h2><p>Return eligibility, exchange conditions, and applicable time limits are determined by our current return policy and the details provided with your order. Contact <a className={styles.contact} href="mailto:hello@nemo.com">hello@nemo.com</a> before sending an item back so we can guide you through the process.</p></div></section>
    <section className={styles.section}><p className={styles.index}>05</p><div><h2>Content and responsibility</h2><p>You keep ownership of content you submit, but give NEMO permission to display it as needed to operate the service. We may remove content that violates these terms.</p><p>To the extent permitted by law, NEMO is not responsible for indirect losses arising from use of the store, unavailable services, or delayed deliveries. Nothing here limits rights that cannot legally be limited.</p></div></section>
    <section className={styles.section}><p className={styles.index}>06</p><div><h2>Changes</h2><p>We may update these terms as the store changes. The latest version will be posted on this page, with the update date shown below. Continued use of NEMO after an update means you accept the revised terms.</p><p>Last updated: August 27, 2026.</p></div></section>
  </div></main>
}
